---

dist: noble

language: python
python:
  - "3.13"
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://apt.releases.hashicorp.com noble main'
        key_url: 'https://apt.releases.hashicorp.com/gpg'
    update: true
    packages:
      - bridge-utils
      - dnsmasq-base
      - ebtables
      - virtinst
      - qemu-kvm
      - qemu-utils
      - libvirt-dev
      - libvirt-daemon-system
      - libguestfs-tools
      - libxslt-dev
      - libxml2-dev
      - zlib1g-dev
      - ruby-dev
      - ca-certificates
      - curl
      - gcc
      - iproute2
      - sudo
      - vagrant

install:
  - sudo gem update --system
  - sudo gem install fog-libvirt --no-document
  - vagrant plugin install vagrant-libvirt
  - pip install wheel pyopenssl tox ansible
  - sudo chmod o+rwx /var/run/libvirt/libvirt-sock

script:
  - mv ../freeipa_server ../tcharl.freeipa_server
  - ansible-galaxy role install -r requirements-standalone.yml
  - ansible-galaxy collection install -r requirements-collections.yml
  - travis_wait 30 tox -e test-exec -- --scenario-name kvm
branches:
  only:
    - master
