---

- name: Freeipa-server | compute server hostname
  ansible.builtin.debug:
    msg: "{{ hostname | default(securehost_current_hostname.stdout if securehost_current_hostname.stdout.endswith(company_domain) else idm_server_default_domain_prefix + '.' + company_domain) }}"
  register: securehost_freeipa_server_host

- name: Freeipa-server | set hostname
  ansible.builtin.include_role:
    name: tcharl.ansible_hostname
  vars:
    hostname: "{{ securehost_freeipa_server_host.msg }}"
    hostname_reboot: false
    ansible_become: true
  when:
    - securehost_freeipa_server_host.msg == idm_server_default_domain_prefix + '.' + company_domain

- name: Freeipa-server | opens freeipa services firewall
  ansible.builtin.include_role:
    name: tcharl.ansible_routing
  vars:
    firewalld_zones:
      - name: public
        enabled_services:
          - service: freeipa-ldap
          - service: freeipa-ldaps
          - service: dns
          - service: https
  tags:
    - dependency

- name: Freeipa-server | configures and installs freeipa server
  ansible.builtin.include_role:
    name: freeipa.ansible_freeipa.ipaserver
  vars:
    ipaserver_ip_addresses: "{{ [securehost_current_host_ip.msg] }}"
    ipaserver_domain: "{{ company_domain }}"
    ipaserver_realm: "{{ company_domain | upper }}"
    ipaserver_forwarders: [ ]
    ipaserver_no_reverse: false
    ipaserver_setup_dns: yes
    ipaserver_setup_kra: yes
    ipaserver_auto_forwarders: yes
    ipaadmin_password: "{{ company_realm_password }}"
    ipadm_password: "{{ company_ad_password }}"
    ipaclient_no_ntp: "{{ True if (ansible_facts['virtualization_type'] is defined and ansible_facts['virtualization_type'] in ['container']) else False }}"
    ansible_become: true
