---

- name: Post_Install | create resolved.conf.d directory
  become: true
  ansible.builtin.file:
    state: directory
    dest: '/etc/systemd/resolved.conf.d'
    mode: "0755"

- name: Post_Install | add internal domain dns
  ansible.builtin.template:
    src: systemd-resolved.conf.d/head.j2
    dest: /etc/systemd/resolved.conf.d/head.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  vars:
    dns_master_ip_to_set: "{{ freeipa_server_exposed_ip }}"
    domain: "{{ company_domain }}"
  register: freeipa_server_resolved_dns_template

- name: Post_Install | restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  when: freeipa_server_resolved_dns_template.changed
  become: true
